### ISSUE TITLE
ISCAN encoding/enriching buttons not working

### ISSUE THREAD

**Issue by vannawillerton** [MontrealCorpusTools/polyglot-server#1]
In corpus summary view, all **Encode new property**, **Encode new subset**, and **Enrich xx from CSV file** buttons not working (to be specific, nothing at all happens when I press them). The database for the corpus is running and buttons to reach query view all work fine. I've tried with two different corpora.

**Comment by mmcauliffe** [comment]
Resolved by new enrichment
