### ISSUE TITLE
Enrichment errors keeping corpus busy

### ISSUE THREAD

**Issue by MichaelGoodale** [MontrealCorpusTools/polyglot-server#101]
Sometimes, when running enrichments which fail, the corpus hangs as 'busy' even though the celery task has already errored out. We should see why this isn't be handled by [this](https://github.com/MontrealCorpusTools/polyglot-server/blob/6f9258a588f84877bfc51fe09193066eefefc701/pgdb/models.py#L806).

**Comment by EJMarshall1** [comment]
Hi @MichaelGoodale, I'm having a similar issue. I was removing the enrichments to retry the tutorial from the start. However, I removed the enrichments in the wrong order. This meant that some enrichments are no longer runnable - but it says "corpus busy" and I can no longer remove them or reset them. Cheers, Edward.
