### ISSUE TITLE
Logged out - corpus still available

### ISSUE THREAD

**Issue by EJMarshall1** [MontrealCorpusTools/polyglot-server#103]
Hi, when I log out of ISCAN from any corpus summary page, the page/tab remains accessible after I have logged out. Thanks, Edward 

![screen shot 2018-08-06 at 21 56 22](https://user-images.githubusercontent.com/41968455/43740610-a0418146-99c3-11e8-810e-8282c97a29b4.png)

**Comment by msonderegger** [comment]
looks like a bug..
