### ISSUE TITLE
Unauthorised access page when logged out

### ISSUE THREAD

**Issue by MichaelGoodale** [MontrealCorpusTools/polyglot-server#104]
Currently, when logged out, you can still access pages by typing in their URL, there's no redirection to an "Unauthorised access" page. While this isn't a big issue as the API calls are still blocked so no damage can be done, it's a little jarring that you can still access them.

I tried briefly implementing this but I wasn't really familiar with how auth was set up on the front end, maybe a task for @mmcauliffe in the future?

**Comment by msonderegger** [comment]
Yes, good catch -- sounds like @mmcauliffe should deal with in future or
show you how.

**Comment by msonderegger** [comment]
@mmcauliffe agreed this is no longer low-priority given that ISCAN prototype will become public at workshop?
