### ISSUE TITLE
Syllables enrichment - 'Syllabics' not an option in phone subset menu

### ISSUE THREAD

**Issue by jo-pearce** [MontrealCorpusTools/polyglot-server#120]
When using Chrome and following the ISCAN Tutorial 1, I encountered the following problem: To encode the 'Syllables' enrichment, the tutorial asks you press the 'Syllables' button under the 'Annotation levels' header, then to select Max Onset from the Algorithm dropdown menu and select 'Syllabics' from the Phone Subset menu. However, 'Syllabics' is not an option in the Phone Subset menu - the only is option you can select is 'Sibilants'.
![syllabics](https://user-images.githubusercontent.com/42466235/44260614-dc0dcf80-a20c-11e8-8e8e-d7a5336466b8.png)

**Comment by MichaelGoodale** [comment]
Hi!
Did you run the enrichment to encode syllabics? Initially the syllabic subset of phones doesn't exist, you have to go to "Phone subset" enrichment(i.e. do the same process you did for sibilants.) 

If you did run the syllabic enrichment, maybe try deleting the syllabic enrichment and re-running it.

Thanks!

**Comment by jo-pearce** [comment]
Hi! Thanks, that's exactly it! What happened was that the button for 'select syllabics" wasn't working for me when I was on the "phone subset" enrichment (a couple of others have noted they have had this issue as well on Slack, not sure if it has been noted here yet), so I must have just skipped over it instead of selecting it manually and then forgotten that I had done that.

**Comment by msonderegger** [comment]
Thanks -- and glad to have you on board, Jo.
