### ISSUE TITLE
Query / Results GUI 

### ISSUE THREAD

**Issue by EJMarshall1** [MontrealCorpusTools/polyglot-server#121]
Hi there, 

1. On the query page results section - would it be possible to make it so that columns maintain a fixed width showing all of the characters contained within and then add a scroll bar so that you can see all of the data selected? (Cosmetic) 

![query1](https://user-images.githubusercontent.com/41968455/44343080-d6baba00-a484-11e8-8a57-b71ab6ca1c61.PNG)

2. On a similar note, there appears to be a maximum number of columns you can select before you cannot successfully export the data as a CSV. 

3. Query page - 'word' filter - because the length of the filter names you have to scroll across to check the box, but you can only do this at the bottom of the window. This is a bit clunky. (low priority) 

![query2](https://user-images.githubusercontent.com/41968455/44343193-32854300-a485-11e8-859c-4f0cb04a8f8e.PNG) ![query 3](https://user-images.githubusercontent.com/41968455/44343201-35803380-a485-11e8-840f-a0d18f7de7e9.PNG)

4. The buttons for changing the page of results which was fixed previously seems to have stopped working. It doesn't seem to work even when you only have one column selected. But, bizarrely when I click on a page number it will change to that page if I click export as CSV, but it doesn't actually export the data as a CSV. 

Thanks, 

Edward

**Comment by EJMarshall1** [comment]
Also, would it be possible to display the total number of tokens when the query has run? I know you can see how many tokens there are when you click 'view detail' but I think it would be good to see on the query / results page.

**Comment by msonderegger** [comment]
Hi @EJMarshall1 -- thanks for these suggestions. Just for triaging and implementation, could you break these up into four "issues"?  It looks like (1) and (3) are enhancements and (2) and (4) are bugs.
