### ISSUE TITLE
Speed of acoustics track export

### ISSUE THREAD

**Issue by msonderegger** [MontrealCorpusTools/polyglot-server#122]
MM has been working on this for a while -- export of anything involving a pitch track or similar is currently too slow.

Progress is all in Michael's head,  I am just making an issue here to track because it's a major outstanding thing.

This is crucial for us being able to do _any_ example where you export tracks or aggregate functions over them (like mean F0 for every X vowel).... which is basically anything intonation-related (or IF0).

**Comment by mmcauliffe** [comment]
Resolved in PolyglotDB.
