### ISSUE TITLE
Enrichment Pauses typo and scroll function not available

### ISSUE THREAD

**Issue by staceyharkin** [MontrealCorpusTools/polyglot-server#132]
ISCAN Tutorial 1: Sibilant states 'For our tutorial corpus, we just need to tick the box under ‘Include’ for the word marked <sil>', but this has been changed to 'Label as pause' and '<SIL>' in ISCAN. 

Also, the scroll function is not currently available in Chrome to view all 25 options.

Please see attached.

![image](https://user-images.githubusercontent.com/42970736/45037057-00afd700-b056-11e8-87f2-0c5f0457f7a1.png)

**Comment by staceyharkin** [comment]
Similarly, under 'hierarchical property' the tutorial states 'This will bring you to a page with three drop down menus (Higher annotation, Lower annotation, Property type)', but the view is of four drop down menus with the headings 'Higher linguistic type', 'Lower linguistic type: (optional)', 'Subset of lower linguistic type' and 'Property type'. 

![image](https://user-images.githubusercontent.com/42970736/45038548-5639b300-b059-11e8-9a16-d40752b2835f.png)

**Comment by mmcauliffe** [comment]
Closing this on the dev side, the docs will have to be updated as part of the interface update.
