### ISSUE TITLE
string properties in query issues

### ISSUE THREAD

**Issue by msonderegger** [MontrealCorpusTools/polyglot-server#135]
Related to #65 

auto-complete doesn't happen for some prefixes, such as 's'  (using spade-Icecan):

![screen shot 2018-09-08 at 8 13 47 am](https://user-images.githubusercontent.com/798417/45254060-2fbc9600-b33f-11e8-867d-70833e6595f4.png)

should show `S` and `SH`

similarly when `SH` is input:

![screen shot 2018-09-08 at 8 14 35 am](https://user-images.githubusercontent.com/798417/45254063-42cf6600-b33f-11e8-97b8-5f3c557bf0c7.png)

**Comment by mmcauliffe** [comment]
Looks like you just have to hard refresh it to fix it.

**Comment by msonderegger** [comment]
looks good now!
