### ISSUE TITLE
Previous & following in export

### ISSUE THREAD

**Issue by msonderegger** [MontrealCorpusTools/polyglot-server#136]
currently, if previous or following (or previous previous, etc.) unit X weren't part of the query, info about them cannot be included in the export. It is necessary to edit the _query_:
- click (e.g.) "Add previous"
- then click "Refresh"

for properties of (e.g.) previous phone to appear in the export checkbox menu.

I realize the underlying issue here (previous phone info not available at all if not in original query), but this behavior is pretty non-intuitive for a user and info about preceding and following units are common, including in tutorial cases (IF0).

@mmcauliffe how should we address this?  Options:

- For Alpha 3, users just have to be manually instructed (in documentation) to do steps above

- For Alpha 3, implement functionality where you can click "previous" or "following" within export, and this either automatically adds to query and refreshes results, or message pops up telling user what to do.

**Comment by mmcauliffe** [comment]
I would vote to add it in the documentation, less work, and I don't have any immediate ideas on how to implement option 2 cleanly.
