### ISSUE TITLE
Corpus View Text Overlap

### ISSUE THREAD

**Issue by vannawillerton** [MontrealCorpusTools/polyglot-server#146]
In newest Chrome version (not firefox) there is a text overlap at the top of the corpus summary view -- see screenshot.

![screenshot from 2018-10-04 08-57-47](https://user-images.githubusercontent.com/35343316/46475540-c7cd6400-c7b3-11e8-9305-981f0fae3a71.png)

**Comment by msonderegger** [comment]
true for me as well (Chrome 69.0.3497.100 on OS X).

**Comment by vannawillerton** [comment]
![screenshot from 2018-10-04 09-09-24](https://user-images.githubusercontent.com/35343316/46476056-3b23a580-c7b5-11e8-95a3-cae7cad5124d.png)

Another one in Enrichment View > encode pauses.

**Comment by JaneStuart-Smith** [comment]
This is also true for me (google chrome from Windows)
![textbitwierdafter_import](https://user-images.githubusercontent.com/43891160/46552726-7ae0af00-c8d3-11e8-8e2f-afd75f1e4dd0.PNG)
