### ISSUE TITLE
Refined formant enrichment interface

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/polyglot-server#16]
Add extra interface options to acoustics enrichment that allow for uploading a vowel prototypes csv file (similar to uploading a praat script).  Also add option for number of iterations and duration threshold (see https://github.com/MontrealCorpusTools/polyglot-server/blob/master/pgdb/models.py#L882) for where to use these when the enrichment is running.

Validation for number of iterations:
- Must be coerceable to an integer
- Must not be blank

Validation for duration threshold
- Can be blank
- If not blank, must be coerceable to a float

Validation for vowel prototypes csv
- Can be blank

**Comment by MichaelGoodale** [comment]
Implemented in PR #24
