### ISSUE TITLE
Allow for encoding stress on syllables from word stress patterns

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/polyglot-server#20]
If the stress pattern word property exists and syllables have been encoded, it should be possible to run an enrichment through ISCAN that calls encode_stress_from_word_property (https://github.com/MontrealCorpusTools/PolyglotDB/blob/master/polyglotdb/corpus/syllabic.py#L417).

This should have a selectable word property dropdown to choose from.  Probably also have some validation that the column is indeed a stress pattern format column (i.e., string, digits and dashes).

Additionally, the API will also have to be updated so that the Enrichment model's run_enrichment function can detect this new type of enrichment.

The enrichment type is related to hierarchical properties, so can be grouped with them on the right side menu of the enrichment page.

**Comment by msonderegger** [comment]
Is there a reason this is a separate button on the same level as Hierarchical Properties?  I thought it actually _is_ a hierarchical property (and would just be a new kind of property). Or @mmcauliffe , you thought this way better?
