### ISSUE TITLE
Rename discourses in ISCAN to sound files

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/polyglot-server#25]
Sound files is a more transparent name of what discourses represent (originally used as a catchall for analyzing text files with no sound files and annotated sound files).  Since all analysis in ISCAN is based on sound files, that should be more easily understandable by users than "discourses".

**Comment by MichaelGoodale** [comment]
Does it make sense to leave the code labeling discourses as discourses while making only what's displayed to the user "sound-files"?

**Comment by mmcauliffe** [comment]
Yes, this would only be a display change on the web app side, anything referencing like `c.discourses` etc in the API should remain.
