### ISSUE TITLE
Encode phone subset functionality

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/polyglot-server#3]
Under the Phones section, ensure that new subsets can be encoded.

Specifically, clicking the button should go to a new page with fields for:

* Label of the subset
* Selection of phones
* Accept/Cancel buttons

For selection of phones, take a look at the query interface, where the dropdown labelled "All" that allows you to select subsets to use in queries should be a good widget to use initially.

When Accept gets pushed, get redirected to the corpus page again and a new Enrichment should be made via a REST call to the Enrichment service.

**Comment by a-coles** [comment]
Resolved in PR for [phone subsets](https://github.com/MontrealCorpusTools/polyglot-server/pull/10).
