### ISSUE TITLE
Mousing over a not-runnable icon for enrichment should give a tooltip for why its not runnable

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/polyglot-server#36]
So for instance, if a speech rate enrichment is made for utterances, but utterances are not encoded, it should say that "Utterances must be encoded".

This is will probably involve a change to the API such that it returns a runnable error message if it's not runnable, and an empty string if it is runnable.

**Comment by msonderegger** [comment]
I was going to say that this seems ambitious, but it's done already!
