### ISSUE TITLE
Add error message when trying to do anything with a Corpus when its database is not running

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/polyglot-server#37]
For now aspects like the corpus/query pages should be disabled, with a link to the database page.

Eventually we might want something more like automatically starting the database for the requested corpora.

**Comment by msonderegger** [comment]
I was just able to click import for `spade-sotc` despite it not being running (on roquefort), and I get the normal message:

"The spade-SOTC corpus is currently importing, please be patient."

**Comment by MichaelGoodale** [comment]
Was the warning still present? The one that says `The spade-ICE-Can corpus is not currently running, please start it at databases.`

**Comment by msonderegger** [comment]
Nope. maybe the version on roquefort doesn't have this pulled in yet?
