### ISSUE TITLE
Rerunning/resetting enrichment

### ISSUE THREAD

**Issue by a-coles** [MontrealCorpusTools/polyglot-server#4]
On Firefox and Chrome, accessing on roquefort from oka:

Attempting to resent enrichments by clicking the `Reset` button in the corpus view appears to do nothing. After a hard refresh, the other button for the enrichment still reads `RerunEncode`.

Similarly, clicking the `RerunEncode` buttons seems to do nothing, but this is less transparent since the logs are not available to the browser. Transparency could be increased by setting the button to read `Rerunning...` while the re-encoding is occurring and back to `RerunEncode` when it has finished.

**Comment by mmcauliffe** [comment]
Resolved by new enrichment pages
