### ISSUE TITLE
Phones take too long to load in subset selection

### ISSUE THREAD

**Issue by MichaelGoodale** [MontrealCorpusTools/polyglot-server#43]
Right now it takes a few seconds for the phones to load under subset selection. I don't see any reason why this database query should take so long, there's probably a way to get it to work faster.

**Comment by mmcauliffe** [comment]
If the profiling shows that it's on the PolyglotDB end, I can give some pointers for what could be causing it.  The type-based `query_lexicon` should be fast though.

**Comment by mmcauliffe** [comment]
Seems fast enough now.
