### ISSUE TITLE
Add duration as a column for export and filtering

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/polyglot-server#49]
Should be available for all annotation types

**Comment by mmcauliffe** [comment]
I think the easiest place to add this is here for the moment: https://github.com/MontrealCorpusTools/polyglot-server/blob/master/pgdb/serializers.py#L48

where at the moment it returns something like:

```
{
'phone': [('label', ''), ('begin', 0), ('end', 0)],
'word'...
}
```

and we want it to return:

```
{
'phone': [('label', ''), ('begin', 0), ('end', 0), ('duration', 0)],
'word'...
}
```

I think a fix for this in PolyglotDB would be good too, since there's no real reason duration isn't available there and there are some hacks that could be removed by putting this in the hierarchy.  But that would probably necessitate rebuilding corpora, so we'll want a check in polyglot-server for now that makes sure all linguistic types have a duration token property.

**Comment by msonderegger** [comment]
@MichaelGoodale for an example of why this is needed, see [here](https://speech-corpus-tools.readthedocs.io/en/latest/tutorial/tutorial.html#example-1-factors-affecting-vowel-duration) in SCT tutorial.  We want to be able to export things like:
- duration of a phone (for phone queries)
- duration of the *word* containing the phone (for phone queries)

etc.

as columns of the eventual CSV.
