### ISSUE TITLE
Add interface for alignment filters

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/polyglot-server#50]
Should be able to filter to find syllables/phones of utterance-final words (words aligned to the right edge of utterances)

**Comment by mmcauliffe** [comment]
I think the simplest way for now is to do a dropdown menu for whether this X should be right aligned to a higher linguistic type and one for whether this X should be left aligned.

**Comment by msonderegger** [comment]
@MichaelGoodale (or anyone who ends up doing this) : for background on what "alignment filters" means, see here:

https://speech-corpus-tools.readthedocs.io/en/latest/additional/filters.html

where there's an explainer with graphics, as well as here:

https://speech-corpus-tools.readthedocs.io/en/latest/additional/buildingqueries.html

where alignment as part of queries more generally is discussed.

The [vowel duration example](https://speech-corpus-tools.readthedocs.io/en/latest/tutorial/tutorial.html#example-1-factors-affecting-vowel-duration) in SCT tutorial shows an example where alignment filters are used.
