### ISSUE TITLE
Start enrichment table as blank?

### ISSUE THREAD

**Issue by msonderegger** [MontrealCorpusTools/polyglot-server#51]
At the moment when a corpus is imported, the table in `enrichment` view shows up populated with some default rows.

I can't decide whether this is desirable or now, since it's not transparent what these defaults do and if the user can just click "Encode syllabics" or has to / should actually create a new enrichment.

OTOH I can see the value to having some sensible defaults pre-loaded.

Any thoughts?  Maybe we should at least put "(default)" at the end of the name of each enrichment that is there by default?

**Comment by MichaelGoodale** [comment]
I think this was covered by #31

**Comment by mmcauliffe** [comment]
Yeah, it should be currently blank.  I think reasonable defaults would encoding pause with whatever the most common word at the initial import (should be something like "<SIL>"), and encoding utterances with 150ms threshold, since utterances are on the more fundamental side.

**Comment by msonderegger** [comment]
It's not blank after I imported Buckeye (yesterday) on current roquefort version.   is this a bug or the version there is out of date?

**Comment by msonderegger** [comment]
confirmed; now shows up as blank. weird.
