### ISSUE TITLE
Access to previous and following annotations in query/export

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/polyglot-server#53]
For instance, following and previous phones should be queryable and columns from them should exportable (i.e., is the previous consonant "voiced").

**Comment by msonderegger** [comment]
Here "columns" means "properties of phones", I believe.

SCT tutorial [example 1](https://speech-corpus-tools.readthedocs.io/en/latest/tutorial/tutorial.html#example-1-factors-affecting-vowel-duration) shows some example use cases.

**Comment by msonderegger** [comment]
We've modified this to be:

- MM will implement just _one_ preceding + following phone interface, so it's clear what the vision is and a basic version works. Ideally by Aug 2

- Next: hand off to MG who will work out how to expand for arbitrarily previous or following phones/etc. (Ex: previous previous phone)
