### ISSUE TITLE
Utterance view navigation

### ISSUE THREAD

**Issue by a-coles** [MontrealCorpusTools/polyglot-server#6]
In Firefox, accessing on roquefort from oka, using a desktop + mouse with scroll wheel:

* Pressing space automatically scrolls the browser down one viewport's worth, instead of playing the audio.
* Scrolling over the textgrid/spectrogram/waveform appears to just scroll the entire page, instead of zooming or shifting the utterance.

In Chrome:

* I can sometimes "catch" the utterance when scrolling over it at a particular speed (too fast or too slow will simply scroll the entire page), which results in zooming, but the "right" way to do this is not at all transparent, and the behavior seems finicky.

These problems might be addressed by a more explicit scroll bar and zoom in/out buttons.

**Comment by mmcauliffe** [comment]
Plots for the detail view should now resize based on the window, so there shouldn't be any scrolling issues now.

**Comment by msonderegger** [comment]
works for me!
