### ISSUE TITLE
Duration Threshold units

### ISSUE THREAD

**Issue by msonderegger** [MontrealCorpusTools/polyglot-server#60]
Under corpus view->`Enrichment`->`Acoustics` then `Analysis` = `Fave-style point formants`, it's unclear what the units of "duration" are. Add 'msec' or 'sec' in parens.  (I hope it's msec; if not, the input needs to be changed to allow non-integer values)

**Comment by MichaelGoodale** [comment]
According to the docstring on polyglot DB, it's milliseconds.

**Comment by mmcauliffe** [comment]
It's actually in seconds, the doctstring is inaccurate in this case, so conversion on polyglot-server end is necessary if the field stays in millisecond
