### ISSUE TITLE
Add dropdown for operators in query

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/polyglot-server#64]
Currently implicitly `==`, should be able to specify: 
- `==`
- `!=`
- `<`
- `>`
- `<=`
- `>=`

**Comment by MichaelGoodale** [comment]
#63  would be subsumed by this issue right?

**Comment by msonderegger** [comment]
I'm not sure whether is actually subsumed, because "not in a subset" may be dealt with differently than "not equal to"... right @mmcauliffe?  (The former is "not in set X", as opposed to "not X".)
