### ISSUE TITLE
can't delete FAVE-style formants enrichment from table

### ISSUE THREAD

**Issue by msonderegger** [MontrealCorpusTools/polyglot-server#69]
I created a FAVE-style formants enrichment in the enrichment table for Buckeye:
![screen shot 2018-07-27 at 9 51 26 am](https://user-images.githubusercontent.com/798417/43324700-ca44d4be-9182-11e8-942b-db27e388854d.png)

but `Run` is grayed out and I'm not sure why. (A `vowels` subset of phones is encoded already.)

So I was trying to delete the row to redo it, but get a pop-up message on clicking `Delete` for formants1`:
![screen shot 2018-07-27 at 9 53 48 am](https://user-images.githubusercontent.com/798417/43324780-faf5a5ca-9182-11e8-8c3d-d61a96071c6d.png)

**Comment by MichaelGoodale** [comment]
It probably can't be run because I *think* the initial FAVE subset is `vowel` not `vowels`.

**Comment by mmcauliffe** [comment]
That shouldn't matter too much, since you can select the subset to use, right?
