### ISSUE TITLE
enrichment/pauses page opaque for new users

### ISSUE THREAD

**Issue by vannawillerton** [MontrealCorpusTools/polyglot-server#70]
As a new user it was unclear what in this page I should be selecting and what the results of my choice would be. 

Some additional instructions appearing on this page would be helpful just describing why we should encode pauses, what the result of encoding pauses is and what I should look for and select to do so. 

(I'm referring to the page that comes up when you go from the 'Enrichment view' and press the 'pauses' button under the 'Annotation levels' header)

**Comment by MichaelGoodale** [comment]
I've simplified the layout of it considerably, it should be more intuitive. I'm not sure about embedding documentation into the page though, I don't know what the best course of action is for explaining what stuff does is. It seems it would be odd to only explain what pauses are and not all enrichments.

**Comment by msonderegger** [comment]
@vannawillerton @MichaelGoodale yes, let's hold off on embedding documentation for now. This is something we'll start doing in... maybe Alpha 3.  There are some high-level decisions to make first about where documentation motivating things goes. (My current thinking is in the ReadTheDocs help that will exist -- linked to from relevant ISCAN pages -- but this can be modified based on user feedback.)

**Comment by msonderegger** [comment]
@MichaelGoodale I think it looks better at least, thanks!

(NB: there's a misspelling though)
