### ISSUE TITLE
Dropdown Menus Not Properly Populated: enrichment/hierarchical-property page 

### ISSUE THREAD

**Issue by vannawillerton** [MontrealCorpusTools/polyglot-server#72]
From the Enrichment View, when you select the 'Hierarchical property' button it brings you to a page with three dorpdown menus: Higher Annotation, Lower Annotation, and Property Type. I know that **Higher Annotation** is supposed to at least be populated with 'Utterance', 'Word', and 'Syllable', and **Lower Annotation** is supposed to have options at least for 'Syllable', and 'Phone'. 

However, **Higher** only has the option for 'word': 
![screenshot from 2018-07-27 10-24-42](https://user-images.githubusercontent.com/35343316/43327301-0ad58108-9189-11e8-9bd9-e8dd263c6727.png)

And **Lower** initially has no options:
![screenshot from 2018-07-27 10-24-47](https://user-images.githubusercontent.com/35343316/43327316-171c0518-9189-11e8-8335-f1f7a9c42b98.png)

If I select 'word' from **Higer**, then an option in **Lower** is made available:
![screenshot from 2018-07-27 10-25-05](https://user-images.githubusercontent.com/35343316/43327358-3338d438-9189-11e8-8280-69bc4793dd80.png)

**Property Type** has three options in all cases, so I think that one is fine:
![screenshot from 2018-07-27 10-24-50](https://user-images.githubusercontent.com/35343316/43327437-6d37063c-9189-11e8-8faa-5597ed4db38f.png)

**Comment by msonderegger** [comment]
yes all makes sense, good catch
