### ISSUE TITLE
"encoded acoustics" confusing

### ISSUE THREAD

**Issue by msonderegger** [MontrealCorpusTools/polyglot-server#73]
Currently in the Corpus view, if you've encoded FAVE-style formants or spectral measures, these will show up under "Currently encoded properties" for Phones, but nothing will show up under "Currently encoded acoustics" for Acoustics. 

I see the logic of this (FAVE-style formants are single measures that are properties of phones), but it's potentially confusing because the user originally clicked "Acoustics" to make the enrichment.

I think Acoustics in corpus view currently only shows encoded _tracks_. maybe it should show point measures as well, even if these are duplicates? not sure..

**Comment by mmcauliffe** [comment]
An easy fix would be to be explicit that it's only encoded tracks that are listed there?

The issue with point measurements showing up there is that there's no difference in the database between F1 and begin.  If we wanted them there then the Enrichment object would have to know what it's encoding, which it currently doesn't.

**Comment by msonderegger** [comment]
I think it's fine they show up there.  I was thinking maybe _also_ under Acoustics, but perhaps that's confusing.

Maybe just change "Acoustics" in corpus view to "Acoustic tracks" or something?

**Comment by mmcauliffe** [comment]
Yeah, changed it to acoustic tracks, which are in their own section because the point measures already have a way to view if they're encoded.

**Comment by msonderegger** [comment]
Great.  

Btw should I have marked this low-priority? I guess I have been assuming that "suggestion" implies low-priority. (This issue didn't need to be addressed ASAP.)
