### ISSUE TITLE
'word_surface_transcription' not visible for Buckeye

### ISSUE THREAD

**Issue by msonderegger** [MontrealCorpusTools/polyglot-server#75]
after importing Buckeye corpus and trying to set up an export of a phone query, where each word's "surface_transcription" is a column, I see this (rightmost column):

![screen shot 2018-07-27 at 11 11 50 am](https://user-images.githubusercontent.com/798417/43329353-1dc4a15e-918e-11e8-8b93-09a8b7c6a072.png)

**Comment by mmcauliffe** [comment]
This is fixed by the latest PolyglotDB build
