### ISSUE TITLE
Multiple databases running for same corpora?

### ISSUE THREAD

**Issue by msonderegger** [MontrealCorpusTools/polyglot-server#79]
I am just pre-thinking of a problem that is already coming up with just two active users (me, Vanna): what if more than one user is working on the same corpus?  (Ex: two people doing the tutorial using logins on roquefort)

Would it be easy to make a way for there to be multiple databases started up corresponding to the same corpus -- like, SPADE-IceCan-morgan and SPADE-Icecan-vanna -- or would we literally need to put a new repo up in the same data directory on roquefort that's a duplicate of SPADE-IceCAN?

**Comment by mmcauliffe** [comment]
There are some locking mechanisms in place to prevent multiple users from being an issue (though there of course might be bugs).  In general at this stage we want to support multiple users per database/corpus, since otherwise we're going to run out of memory/disk space fast.

**Comment by msonderegger** [comment]
Ok that makes sense to me. We’ll just need to think about how the tutorial
phrases things re other possible users.

Maybe this is all an argument for trying to move more quickly than
anticipated to polyglot servers running at other sites, which should be
doable given docker.

**Comment by msonderegger** [comment]
Thinking about this a bit more: I totally agree that we want to assume multiple users per corpus, and I don't want to overthink before we have multiple users online, but I also want the tutorial rollout to go smoothly.

How about this: we'll create 3 new copies of ICE-Can, just called
spade-tutorial-1
spade-tutorial-2
spade-tutorial-3

and for the moment, we will just say explicitly in the tutorial:
- Make a post to "ISCAN tutorial status" page when you're doing tutorial on one of these: say which one.
- When you're done with the tutorial, reset the dataset (with instructions how), and make a Basecamp post saying no longer using the dataset.

this is hacky but will let us do rollout imminently, using Vanna's current tutorial.

My thinking is:
- ICE-Can is just 13G so this won't nuke roquefort.

- Over the rest of this week, we can replace these tutorial datasets with a small subset from ICE-Can (and Vanna can spot check to make sure all runs OK).

- In principle this setup minimizes the need to bug you to set up/restart new datasets, until we have a more principled soltuion in place.

- We add getting such a solution in place part of Alpha 2. (I am leaning towards your idea of having a special set-up just for a "tutorial" dataset, which is very low-footprint.)

**Comment by msonderegger** [comment]
> <@U65FZQU90>: OK, plan for new users has been hashed out with MM and some changes required in documents.

- We are going to create a new repo that is a subset of ICE-Can, called spade-tutorial .  You should do this. We need a subset of about 1/10 the size of ICE-Can, so maybe it'll contain 1-2 speakers.

- Change the tutorial to refer to the tutorial-username dataset (like "tutorial-morgan") instead of ICE-Can

- When a new user is created, say `morgan`, you create a new directory in the repo dir on roquefort, called `spade-tutorial-morgan` (replace "morgan" with username), and give the user _just_ permission to access that dataset, as well as (just so they have some variety) the spade-icecan and spade-buckeye datasets.  <@U0J6VBHHS> will tell you now how to do this (permission aspect).

so the user will basically be working just with the spade-tutorial-USERNAME tutorial for purposes of completing the tutorial(s), and the tutorial text can reflect this.  (note that the normal ISCAN use case is multiple users per dataset, but for the tutorial, it makes sense for a user to have a personal dataset.)

does that make sense?
<sub>[View in Slack](https://mclinglabs.slack.com/archives/CB25GHZH6/p1532978892000296)</sub>
