### ISSUE TITLE
FAVE-like formants minimum iterations & default?

### ISSUE THREAD

**Issue by msonderegger** [MontrealCorpusTools/polyglot-server#80]
generating FAVE-style formants with iterations = 1 terminates quickly and seems to give nothing, when I tried it. 

Is that correct, or a bug? Assuming it's not a bug (maybe iterations = 1 just returns the prototypes?), maybe we should set a minimum value for # iterations, as well as a default. (3?)

**Comment by mmcauliffe** [comment]
Mainly related to #82 for why it didn't run, default for iteration should be 1 or the 5 that Jeff originally implemented.
