### ISSUE TITLE
Formants not encoded?

### ISSUE THREAD

**Issue by msonderegger** [MontrealCorpusTools/polyglot-server#82]
For both Buckeye and SOTC, I have (using current version of ISCAN on roquefort):

- Imported corpus
- encoded a phone subset called `vowels1`
- made an enrichment to generated FAVE-style formants with # iterations = 2 for `vowels1` subset
- run that enrichment

The enrichment runs suspiciously quickly (< 1 minute).

So formants should now be encoded, and F1, F2, etc. do show up under Phone properties in corpus view. But when I do a query on phones looking just for phones in `vowels1` and add the columns for F1 F2 etc. I see nothing:

![screen shot 2018-07-27 at 2 31 22 pm](https://user-images.githubusercontent.com/798417/43340427-48f5717a-91aa-11e8-9c00-9fa055c6aae9.png)

**Comment by msonderegger** [comment]
> OK thanks. I'll file an issue then tagged for Alpha 1 with instructions on reproducing.
<sub>[View in Slack](https://mclinglabs.slack.com/archives/C0ZAQH5ML/p1532716357000320)</sub>

**Comment by msonderegger** [comment]
argh I meant to comment in Slack

**Comment by msonderegger** [comment]
awesome thanks. I won't be able to see this on roquefort but will in tomorrow's build right?

**Comment by mmcauliffe** [comment]
It should be up now, if it's still not working, there's another bug that needs to be fixed.

**Comment by msonderegger** [comment]
Great. @vannawillerton when you have a chance can you check this? You just need to do what it says in my initial post, for some corpus (prob ICE-Can as it's smallest), use Iterations=1, and then make sure you do see numbers in phone_F1, phone_F2 fields.

**Comment by vannawillerton** [comment]
@msonderegger it seems to work fine now
