### ISSUE TITLE
Phone subset names not saving to enrichment table if filled automatically by using preset buttons

### ISSUE THREAD

**Issue by vannawillerton** [MontrealCorpusTools/polyglot-server#88]
In Enrichment View, the name of a new phone subset automatically comes up as *New Phone Subset* if you created the enrichment using one of the preset buttons from the *Create a phone subset* page (This happens in Chrome and Firefox).

If you go to Enrichment > Phone subset, and press either *Select sibilants*, *Select syllabics*, or *Select stressed vowels* buttons, then the **Subset name** box at the top of the page is automatically updated to reflect your choice. For example in this screenshot where all I did was press the *Select stressed vowels* button:

![screenshot from 2018-07-30 14-38-37](https://user-images.githubusercontent.com/35343316/43416740-1ef78c00-9407-11e8-8132-78663f1e5a93.png)

But then when you save and get taken back to the enrichment view, the name that was automatically filled did not get saved I guess and comes up still as *New phone subset*:

![screenshot from 2018-07-30 14-38-56](https://user-images.githubusercontent.com/35343316/43416829-5c3e0d50-9407-11e8-842e-d763d29b62d9.png)

You can get around it by manually changing the subset name and then saving (Like even just erasing and rewriting a single letter), but the automatically generated name should work.

**Comment by MichaelGoodale** [comment]
I actually caught this this morning in #85 . Thanks though! (The subset name is correct, just not the enrichment name, so you can still run it fine).

**Comment by msonderegger** [comment]
Nice catch, both
