### ISSUE TITLE
First tests for ISCAN GUI

### ISSUE THREAD

**Issue by msonderegger** [MontrealCorpusTools/polyglot-server#89]
Write unit tests using Selenium or Karma or similar for testing browser functionality for current ISCAN.

1. Figure out what Selenium/Karma are, and what kind of automated web browsing it can do

2. Write a few tests for basic functionality, in each

3. Figure out which one is better for us (integration with Travis crucial) and post a report (mostly for @mmcauliffe , but I'm also interested).

**Comment by mmcauliffe** [comment]
Travis now passing on master

**Comment by msonderegger** [comment]
👍👍👍
