### ISSUE TITLE
Default new user behavior

### ISSUE THREAD

**Issue by msonderegger** [MontrealCorpusTools/polyglot-server#90]
When a new user is created, by default:

- They should only have permission to see a corpus called spade-tutorial-USERNAME

and a directory spade-tutorial-USERNAME should be created on the server that just copies
`spade-tutorial`
repo

**Comment by msonderegger** [comment]
@mmcauliffe I think we need to make a choice here pre-workshop: do we want this to actually happen fully automatically for any new user, or is the current setup better -- where you (MM) have to manually do these steps?

I could imagine either that (1) full automation is good or (2) that we want to actually make adding users non-trivial at this stage of development.  (Imagine 30 people show up at NWAV workshop -- do we really want to immediately create 30 copies of test corpus on roquefort?)

If (2), we should remove this issue from M3 and instead I'll make issue for docs to make new user request transparent.

**Comment by mmcauliffe** [comment]
New admin function for creating the tutorial corpora per user has been added.  It takes a while to do because it's copying the dataset over, so eventually making it an asynchronous task would be a good idea.
