### ISSUE TITLE
Results UI of query not changing between pages 

### ISSUE THREAD

**Issue by EJMarshall1** [MontrealCorpusTools/polyglot-server#95]
Hi, I can only view one page of results in the web browser. When downloading as .csv all results are visible. Perhaps this is a UI issue with the page buttons? (Sorry if I'm just being dense). 

Page 1:
![page1](https://user-images.githubusercontent.com/41968455/43648993-d6a55786-9733-11e8-9f21-1eb4c6eb5d2d.PNG) 

Page 57: 
![page 57](https://user-images.githubusercontent.com/41968455/43649011-e1e4c190-9733-11e8-9d22-3f3e846ac598.PNG)

Edward

**Comment by MichaelGoodale** [comment]
Hmm, yeah, I got the same thing when I tested it on my machine.

**Comment by MichaelGoodale** [comment]
I tried looking at the `query.js` file to see how to fix pagination but I couldn't quite get my head around how it all worked, @mmcauliffe can you take a look at this bug potentially?

**Comment by msonderegger** [comment]
thanks @EJMarshall1 !
