### ISSUE TITLE
Query page starting point

### ISSUE THREAD

**Issue by EJMarshall1** [MontrealCorpusTools/polyglot-server#97]
Minor suggestion: when you click on "new query" from the corpus summary page, would it be possible to automatically start at the top of the query page? At the moment it seems like something's wrong, but it's not a bug, it just starts at the bottom of the page (and appears to be blank). Thanks, Edward

**Comment by msonderegger** [comment]
I agree!

**Comment by vannawillerton** [comment]
agreed. I keep waiting for the page to load before I remember I just have to scroll up!
