### ISSUE TITLE
Database not running check not performed in the main corpus view.

### ISSUE THREAD

**Issue by MichaelGoodale** [MontrealCorpusTools/polyglot-server#98]
Currently, the database status doesn't update to `S` when the database is not running, and we have only looked at the main corpus view. Once we move to a query page or enrichment page, it updates the status to the correct status, and then displays the "Database not running" warning on both query and corpus pages.

So, the check should also occur on the main corpus page.

**Comment by mmcauliffe** [comment]
I think this is resolved now.
