### ISSUE TITLE
Handling Errors in Enrichment

### ISSUE THREAD

**Issue by vannawillerton** [MontrealCorpusTools/polyglot-server#99]
Currently, when something goes wrong with uploading a file or something in Enrichment view, there is no way for the user to know there has been an error until they try to run it and then running the enrichment hangs for a long time.

There should be some notification telling the user something went wrong before pressing 'Save enrichment'  to save the user some time and confusion.

**Comment by mmcauliffe** [comment]
This should be addressed now.
